"""Update enclosures table

Revision ID: 694b6da6eb6f
Revises: a2857d4225e4
Create Date: 2023-10-16 17:30:48.089221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694b6da6eb6f'
down_revision = 'a2857d4225e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_animals_zookeeper_id_zookeepers'), 'animals', 'zookeepers', ['zookeeper_id'], ['id'])
    op.create_foreign_key(op.f('fk_animals_enclosure_id_enclosures'), 'animals', 'enclosures', ['enclosure_id'], ['id'])
    op.add_column('enclosures', sa.Column('environment', sa.String(length=255), nullable=False))
    op.add_column('enclosures', sa.Column('open_to_visitors', sa.Boolean(), nullable=False))
    op.add_column('zookeepers', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('zookeepers', sa.Column('birthday', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zookeepers', 'birthday')
    op.drop_column('zookeepers', 'name')
    op.drop_column('enclosures', 'open_to_visitors')
    op.drop_column('enclosures', 'environment')
    op.drop_constraint(op.f('fk_animals_enclosure_id_enclosures'), 'animals', type_='foreignkey')
    op.drop_constraint(op.f('fk_animals_zookeeper_id_zookeepers'), 'animals', type_='foreignkey')
    # ### end Alembic commands ###
