"""Add environment column to enclosures

Revision ID: a2857d4225e4
Revises: 31b6688d7074
Create Date: 2023-10-16 17:29:14.538576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2857d4225e4'
down_revision = '31b6688d7074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('animals', sa.Column('species', sa.String(length=100), nullable=False))
    op.add_column('animals', sa.Column('zookeeper_id', sa.Integer(), nullable=True))
    op.add_column('animals', sa.Column('enclosure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_animals_zookeeper_id_zookeepers'), 'animals', 'zookeepers', ['zookeeper_id'], ['id'])
    op.create_foreign_key(op.f('fk_animals_enclosure_id_enclosures'), 'animals', 'enclosures', ['enclosure_id'], ['id'])
    op.add_column('enclosures', sa.Column('environment', sa.String(length=255), nullable=False))
    op.add_column('enclosures', sa.Column('open_to_visitors', sa.Boolean(), nullable=False))
    op.add_column('zookeepers', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('zookeepers', sa.Column('birthday', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zookeepers', 'birthday')
    op.drop_column('zookeepers', 'name')
    op.drop_column('enclosures', 'open_to_visitors')
    op.drop_column('enclosures', 'environment')
    op.drop_constraint(op.f('fk_animals_enclosure_id_enclosures'), 'animals', type_='foreignkey')
    op.drop_constraint(op.f('fk_animals_zookeeper_id_zookeepers'), 'animals', type_='foreignkey')
    op.drop_column('animals', 'enclosure_id')
    op.drop_column('animals', 'zookeeper_id')
    op.drop_column('animals', 'species')
    op.drop_column('animals', 'name')
    # ### end Alembic commands ###
